<?php

/**
 * @file
 * Functions to support theming in the Sass Start theme.
 */



/**
 *  Block suggestions for custom block bundles.
 */
function sass_theme_msd_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['content']['#block_content'])) {
    array_splice($suggestions, 1, 0, 'block__bundle__' . $variables['elements']['content']['#block_content']->bundle());
  }
}